'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HelloWorld.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Australia___Sydney_Opera_House() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Australia - Sydney Opera House", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Brazil___Christ_the_Redeemer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brazil - Christ the Redeemer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Canada__CN_Tower() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Canada -CN Tower", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property China___Great_Wall_of_China() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("China - Great Wall of China", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Egypt___Sphinx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Egypt - Sphinx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property England___Big_Ben() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("England - Big Ben", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ethiopia___Tiglachin_Monument() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ethiopia - Tiglachin Monument", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explore___postcard_cropped_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explore - postcard(cropped)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explore___postcard_cropped_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explore - postcard(cropped)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explore___postcard_cropped_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explore - postcard(cropped)2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property France___Eiffel_Tower() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("France - Eiffel Tower", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Germany___Brandenburg_Gate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Germany - Brandenburg Gate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ghana___independence_arch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ghana - independence arch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property India___Taj_Mahal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("India - Taj Mahal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Israel___Western_Wall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Israel - Western Wall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Italy___Colosseum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Italy - Colosseum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Japan___Hiroshima_Peace_Monument() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Japan - Hiroshima Peace Monument", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Laval_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Laval 3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Level_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Level 3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Level3Background_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Level3Background copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Level3Background_copy1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Level3Background copy1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mexico___Independence_Angel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mexico - Independence Angel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Peru___Machu_Pichu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Peru - Machu Pichu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Philippines___Rizal_Park() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Philippines - Rizal Park", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Russia___Kremelin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Russia - Kremelin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Saudi_Arabia__Mecca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Saudi Arabia -Mecca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property South_Africa___Cradle_of_Humankind() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("South Africa - Cradle of Humankind", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property South_Korea___Dongdaemun_Gate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("South Korea - Dongdaemun Gate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Turkey___Blue_Mosque() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Turkey - Blue Mosque", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property USA___White_House() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("USA - White House", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WorldMap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WorldMap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
