Module capital
    Public canada As String = "Toronto"
    Public usa As String = "Washington"
    Public germany As String = "Berlin"
    Public france As String = "Paris"
    Public england As String = "London"
    Public russia As String = "Moscow"
    Public brazil As String = "Brasilia"
    Public mexico As String = "Mexico City"
    Public peru As String = "Lima"
    Public italy As String = "Rome"
    Public austr As String = "Canberra"
    Public china As String = "Beijing"
    Public japan As String = "Tokyo"
    Public india As String = "New Delhi"
    Public saudi As String = "Riyadh"
    Public sKorea As String = "Seoul"
    Public sAfrica As String = "Pretoria, Cape Town, and Bloemfontein"
    Public turk As String = "Ankara"
    Public egypt As String = "Cairo"
    Public phil As String = "Manila"
    Public ghana As String = "Accra"
    Public ethiopia As String = "Addis Ababa"
End Module
