Module country
    Public canada As String = "Canada"
    Public usa As String = "USA"
    Public germany As String = "Germany"
    Public france As String = "France"
    Public england As String = "England"
    Public russia As String = "Russia"
    Public brazil As String = "Brazil"
    Public mexico As String = "Mexico"
    Public peru As String = "Peru"
    Public italy As String = "Italy"
    Public austr As String = "Australia"
    Public china As String = "China"
    Public japan As String = "Japan"
    Public india As String = "India"
    Public saudi As String = "Saudi Arabia"
    Public sKorea As String = "South Korea"
    Public sAfrica As String = "South Africa"
    Public ethiopia As String = "Ethiopa"
    Public turk As String = "Turkey"
    Public egypt As String = "Egypt"
    Public phil As String = "Philippines"
    Public ghana As String = "Ghana"
End Module
