Module head
    Public canada As String = "Justin Trudeau"
    Public usa As String = "Barack Obama"
    Public germany As String = "Joachim Gauck"
    Public france As String = "Francois Hollande"
    Public england As String = "David Cameron"
    Public russia As String = "Vladimir Putin"
    Public brazil As String = "Dilma Rousseff"
    Public mexico As String = "Enrique Pena Nieto"
    Public peru As String = "Ollanta Humala"
    Public italy As String = "Sergio Mattarella"
    Public austr As String = "Malcolm Turnbull"
    Public china As String = "Xi Jinping"
    Public japan As String = "Shinzo Abe"
    Public india As String = "Pranab Mukherjee"
    Public saudi As String = "Salman bin Abdulaziz Al Saud"
    Public sKorea As String = "Park Geun-Hye"
    Public sAfrica As String = "Jacob Zuma"
    Public turk As String = "Recep Tayyip Erdogan"
    Public egypt As String = "Abdel Fattah el-Sisi"
    Public phil As String = "Benigno Aquino III"
    Public ghana As String = "John Dramani Mahama"
    Public ethiopia As String = "Mulatu Teshome"
End Module
