Module mon
    Public canada As String = "CN Tower"
    Public usa As String = "The White House"
    Public germany As String = "Brandenburg Gate"
    Public france As String = "Eiffel Tower"
    Public england As String = "Big Ben"
    Public russia As String = "Kremlin"
    Public brazil As String = "Christ the Redeemer"
    Public mexico As String = "Chapultepec"
    Public peru As String = "Machu Picchu"
    Public italy As String = "Colosseum"
    Public austr As String = "Sydney Opera House"
    Public china As String = "Great Wall of China"
    Public japan As String = "Hiroshima Peace Monument"
    Public india As String = "Taj Mahal"
    Public saudi As String = "Mecca"
    Public sKorea As String = "Dongdaemun Gate"
    Public sAfrica As String = "Cradle of Humankind"
    Public turk As String = "Blue Mosque"
    Public egypt As String = "Sphinx"
    Public phil As String = "Rizal Park"
    Public ghana As String = "Independence Arch"
    Public ethiopia As String = "Tiglachin Monument"
End Module
